"""Ascend C kernel sources for HQSB S09.

This directory contains Ascend C kernel implementations for the operators
specified in ``docs/stage_experiments/details/S09/``.  The kernels are not
compiled here (no CANN toolchain on this host) but the structure is complete:

* ``common/hqsb_tiling_data.h`` — generated by :mod:`hqsb.ascend.tiling`
* ``add/``, ``reduction/``, ``rmsnorm/`` — each with src/include/tests/bench

The build script ``scripts/ascend/build_ascend_ops.sh`` invokes the CANN
toolchain to compile these kernels for a specific SoC target.  On this host
the scripts will fail with a clear error message rather than silently passing.
"""

from __future__ import annotations

__all__ = [
    "PROVIDER_NAME",
    "KERNEL_NAMES",
]

PROVIDER_NAME = "ascend"

#: Kernel names exposed by this provider.
KERNEL_NAMES = ("add", "row_reduce_sum", "rms_norm")
